// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoApp.Infrastructure.Data;

#nullable disable

namespace TodoApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251228053150_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TodoApp.Domain.Entities.ToDoItem", b =>
                {
                    b.Property<int>("ToDoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ToDoItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ToDoListId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ToDoItemId");

                    b.HasIndex("ToDoListId");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            ToDoItemId = 1,
                            CreatedAt = new DateTime(2025, 12, 28, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(394),
                            Description = "Buy milk, eggs, and bread",
                            DueDate = new DateTime(2025, 12, 29, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(384),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Buy groceries",
                            ToDoListId = 1,
                            UpdatedAt = new DateTime(2025, 12, 28, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(394)
                        },
                        new
                        {
                            ToDoItemId = 2,
                            CreatedAt = new DateTime(2025, 12, 28, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(396),
                            Description = "Annual health checkup",
                            DueDate = new DateTime(2025, 12, 31, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(395),
                            IsCompleted = false,
                            Priority = 3,
                            Title = "Schedule doctor appointment",
                            ToDoListId = 1,
                            UpdatedAt = new DateTime(2025, 12, 28, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(397)
                        },
                        new
                        {
                            ToDoItemId = 3,
                            CreatedAt = new DateTime(2025, 12, 28, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(399),
                            Description = "Finish and submit the quarterly report",
                            DueDate = new DateTime(2025, 12, 30, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(398),
                            IsCompleted = false,
                            Priority = 3,
                            Title = "Complete project report",
                            ToDoListId = 2,
                            UpdatedAt = new DateTime(2025, 12, 28, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(399)
                        },
                        new
                        {
                            ToDoItemId = 4,
                            CreatedAt = new DateTime(2025, 12, 28, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(401),
                            Description = "Discuss project progress with the team",
                            DueDate = new DateTime(2025, 12, 29, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(400),
                            IsCompleted = false,
                            Priority = 1,
                            Title = "Team meeting",
                            ToDoListId = 2,
                            UpdatedAt = new DateTime(2025, 12, 28, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(401)
                        });
                });

            modelBuilder.Entity("TodoApp.Domain.Entities.ToDoList", b =>
                {
                    b.Property<int>("ToDoListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ToDoListId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ToDoListId");

                    b.HasIndex("UserId");

                    b.ToTable("ToDoLists");

                    b.HasData(
                        new
                        {
                            ToDoListId = 1,
                            CreatedAt = new DateTime(2025, 12, 28, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(228),
                            Description = "John's personal task list",
                            Title = "John's Personal Tasks",
                            UpdatedAt = new DateTime(2025, 12, 28, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(229),
                            UserId = 1
                        },
                        new
                        {
                            ToDoListId = 2,
                            CreatedAt = new DateTime(2025, 12, 28, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(230),
                            Description = "Jane's work-related tasks",
                            Title = "Jane's Work Tasks",
                            UpdatedAt = new DateTime(2025, 12, 28, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(231),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TodoApp.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 12, 28, 12, 31, 48, 86, DateTimeKind.Local).AddTicks(9998),
                            Email = "john.doe@example.com",
                            Username = "john_doe"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 12, 28, 12, 31, 48, 87, DateTimeKind.Local).AddTicks(9),
                            Email = "jane.smith@example.com",
                            Username = "jane_smith"
                        });
                });

            modelBuilder.Entity("TodoApp.Domain.Entities.ToDoItem", b =>
                {
                    b.HasOne("TodoApp.Domain.Entities.ToDoList", null)
                        .WithMany("Items")
                        .HasForeignKey("ToDoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TodoApp.Domain.Entities.ToDoList", b =>
                {
                    b.HasOne("TodoApp.Domain.Entities.User", null)
                        .WithMany("ToDoLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TodoApp.Domain.Entities.ToDoList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TodoApp.Domain.Entities.User", b =>
                {
                    b.Navigation("ToDoLists");
                });
#pragma warning restore 612, 618
        }
    }
}
